openapi: 3.0.3
info:
  title: 'Prodict Laravel API'
  description: API文檔
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/employees:
    get:
      summary: 查詢員工
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: page
          description: 頁碼.
          example: 1
          required: true
          schema:
            type: integer
            description: 頁碼.
            example: 1
        -
          in: query
          name: dep_code
          description: 部門編碼.
          example: IT
          required: false
          schema:
            type: string
            description: 部門編碼.
            example: IT
        -
          in: query
          name: keyword
          description: 模糊查詢用戶名稱或信箱.
          example: John
          required: false
          schema:
            type: string
            description: 模糊查詢用戶名稱或信箱.
            example: John
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server Error'
                properties:
                  message:
                    type: string
                    example: 'Server Error'
      tags:
        - Employee
      security: []
    post:
      summary: 新增員工
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 員工名稱.
                  example: John
                email:
                  type: string
                  description: 員工信箱.
                  example: abc@gmail.com
                dep_code:
                  type: string
                  description: 部門編碼.
                  example: IT
                password:
                  type: string
                  description: 密碼.
                  example: '"Ho&FHw.56'
              required:
                - name
                - email
                - dep_code
                - password
      security: []
  '/api/employees/{employee}':
    put:
      summary: 員工修改
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: id
          description: 員工ID
          example: 10
          required: true
          schema:
            type: integer
            description: 員工ID
            example: 10
      responses: {  }
      tags:
        - Employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 員工名稱.
                  example: John
                email:
                  type: string
                  description: 員工信箱.
                  example: abc@gmail.com
                dep_code:
                  type: string
                  description: 部門編碼.
                  example: IT
                password:
                  type: string
                  description: 密碼.
                  example: '(nf:^o'
              required:
                - name
                - email
                - dep_code
                - password
      security: []
    parameters:
      -
        in: path
        name: employee
        description: 'The employee.'
        example: quisquam
        required: true
        schema:
          type: string
  /api/products:
    get:
      summary: 查詢產品
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: page
          description: 頁碼.
          example: 1
          required: true
          schema:
            type: integer
            description: 頁碼.
            example: 1
        -
          in: query
          name: keyword
          description: 模糊查詢產品名稱或內容.
          example: 可食用
          required: false
          schema:
            type: string
            description: 模糊查詢產品名稱或內容.
            example: 可食用
        -
          in: query
          name: id
          description: 員工ID
          example: 20
          required: true
          schema:
            type: integer
            description: 員工ID
            example: 20
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server Error'
                properties:
                  message:
                    type: string
                    example: 'Server Error'
      tags:
        - Product
      security: []
    post:
      summary: 新增產品
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 產品名稱.
                  example: 小米酒
                description:
                  type: string
                  description: 產品說明.
                  example: 可飲用
                price:
                  type: integer
                  description: 價格.
                  example: 100
                stock:
                  type: integer
                  description: 數量.
                  example: 5
              required:
                - name
                - price
                - stock
      security: []
  '/api/products/{product}':
    put:
      summary: 修改產品
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: id
          description: 員工ID
          example: 6
          required: true
          schema:
            type: integer
            description: 員工ID
            example: 6
      responses: {  }
      tags:
        - Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 產品名稱.
                  example: 小米酒
                description:
                  type: string
                  description: 產品說明.
                  example: 可飲用
                price:
                  type: integer
                  description: 價格.
                  example: 100
                stock:
                  type: integer
                  description: 數量.
                  example: 5
              required:
                - name
                - price
                - stock
      security: []
    delete:
      summary: 刪除產品
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: id
          description: 員工ID
          example: 11
          required: true
          schema:
            type: integer
            description: 員工ID
            example: 11
      responses: {  }
      tags:
        - Product
      security: []
    parameters:
      -
        in: path
        name: product
        description: 'The product.'
        example: 9
        required: true
        schema:
          type: integer
tags:
  -
    name: Employee
    description: ''
  -
    name: Product
    description: ''
